export const fonts = {
  'Yeseva One Regular': 'YesevaOne-Regular.ttf',
  Varela: 'Varela.ttf',
  'Unicode BMP Fallback SIL': 'UnicodeBMPFallbackSIL.ttf',
  'Ubuntu Regular': 'Ubuntu-Regular.ttf',
  'Ubuntu Italic': 'Ubuntu-Italic.ttf',
  'Ubuntu Bold Italic': 'Ubuntu-BoldItalic.ttf',
  'Ubuntu Bold': 'Ubuntu-Bold.ttf',
  Roboto: 'Roboto-Regular.ttf',
  'Roboto Italic': 'Roboto-Italic.ttf',
  'Roboto Bold Italic': 'Roboto-BoldItalic.ttf',
  'Roboto Bold': 'Roboto-Bold.ttf',
  'Poppins Regular': 'Poppins-Regular.ttf',
  'Poppins Italic': 'Poppins-Italic.ttf',
  'Poppins Bold Italic': 'Poppins-BoldItalic.ttf',
  'Poppins Bold': 'Poppins-Bold.ttf',
  'Oswald Regular': 'Oswald-Regular.ttf',
  'Oswald Bold': 'Oswald-Bold.ttf',
  'Orbitron Regular': 'Orbitron-Regular.ttf',
  'Orbitron Bold': 'Orbitron-Bold.ttf',
  'Open Sans Regular': 'OpenSans-Regular.ttf',
  'Open Sans Italic': 'OpenSans-Italic.ttf',
  'Open Sans Bold Italic': 'OpenSans-BoldItalic.ttf',
  'Open Sans Bold': 'OpenSans-Bold.ttf',
  'Noto Serif SC': 'NotoSerifSC-Regular.otf',
  'Noto Serif SC Bold': 'NotoSerifSC-Bold.otf',
  'Noto Sans Thai Regular': 'NotoSansThai-Regular.ttf',
  'Noto Sans Thai Bold': 'NotoSansThai-Bold.ttf',
  'Noto Sans TC': 'NotoSansTC-Regular.otf',
  'Noto Sans TC Bold': 'NotoSansTC-Bold.otf',
  'Noto Sans SC': 'NotoSansSC-Regular.otf',
  'Noto Sans SC Bold': 'NotoSansSC-Bold.otf',
  'Noto Sans Mono Regular': 'NotoSansMono-Regular.ttf',
  'Noto Sans Mono Bold': 'NotoSansMono-Bold.ttf',
  'Noto Sans Mongolian Regular': 'NotoSansMongolian-Regular.ttf',
  'Noto Sans Malayalam Regular': 'NotoSansMalayalam-Regular.ttf',
  'Noto Sans Malayalam Bold': 'NotoSansMalayalam-Bold.ttf',
  'Noto Sans KR': 'NotoSansKR-Regular.otf',
  'Noto Sans KR Bold': 'NotoSansKR-Bold.otf',
  'Noto Sans JP Regular': 'NotoSansJP-Regular.ttf',
  'Noto Sans JP Bold': 'NotoSansJP-Bold.ttf',
  'Noto Sans Hebrew Regular': 'NotoSansHebrew-Regular.ttf',
  'Noto Sans Hebrew Bold': 'NotoSansHebrew-Bold.ttf',
  'Noto Sans Display Regular': 'NotoSansDisplay-Regular.ttf',
  'Noto Sans Display Italic': 'NotoSansDisplay-Italic.ttf',
  'Noto Sans Display Bold Italic': 'NotoSansDisplay-BoldItalic.ttf',
  'Noto Sans Display Bold': 'NotoSansDisplay-Bold.ttf',
  'Noto Sans Devanagari Regular': 'NotoSansDevanagari-Regular.ttf',
  'Noto Sans Devanagari Bold': 'NotoSansDevanagari-Bold.ttf',
  'Noto Sans Regular': 'NotoSans-Regular.ttf',
  'Noto Sans Italic': 'NotoSans-Italic.ttf',
  'Noto Sans Bold Italic': 'NotoSans-BoldItalic.ttf',
  'Noto Sans Bold': 'NotoSans-Bold.ttf',
  'Lexend Regular': 'Lexend-Regular.ttf',
  'Lexend Bold': 'Lexend-Bold.ttf',
  'League Spartan Regular': 'LeagueSpartan-Regular.ttf',
  'League Spartan Bold': 'LeagueSpartan-Bold.ttf',
  'Lato Regular': 'Lato-Regular.ttf',
  'Lato Italic': 'Lato-Italic.ttf',
  'Lato Bold Italic': 'Lato-BoldItalic.ttf',
  'Lato Bold': 'Lato-Bold.ttf',
  'Josefin Sans Regular': 'JosefinSans-Regular.ttf',
  'Josefin Sans Italic': 'JosefinSans-Italic.ttf',
  'Josefin Sans Bold Italic': 'JosefinSans-BoldItalic.ttf',
  'Josefin Sans Bold': 'JosefinSans-Bold.ttf',
  'HelveticaRoundedLTStd-Bd': 'HelveticaRoundedLTStd-Bd.otf',
  'HelveticaNeueLTPro-Roman': 'HelveticaNeueLTPro-Roman.otf',
  'HelveticaNeueLTPro-It': 'HelveticaNeueLTPro-It.otf',
  'HelveticaNeueLTPro-BdIt': 'HelveticaNeueLTPro-BdIt.otf',
  'HelveticaNeueLTPro-Bd': 'HelveticaNeueLTPro-Bd.otf',
  'Galada Regular': 'Galada-Regular.ttf',
  'Fraunces 72pt Regular': 'Fraunces72pt-Regular.ttf',
  'Fraunces 72pt Italic': 'Fraunces72pt-Italic.ttf',
  'Fraunces 72pt Bold Italic': 'Fraunces72pt-BoldItalic.ttf',
  'Fraunces 72pt Bold': 'Fraunces72pt-Bold.ttf',
  'Dancing Script Regular': 'DancingScript-Regular.ttf',
  'Dancing Script Bold': 'DancingScript-Bold.ttf',
  'Cabin Regular': 'Cabin-Regular.ttf',
  'Cabin Italic': 'Cabin-Italic.ttf',
  'Cabin Bold Italic': 'Cabin-BoldItalic.ttf',
  'Cabin Bold': 'Cabin-Bold.ttf',
  'Berlin Sans FB Demi Bold': 'BerlinSansFBDemi-Bold.ttf',
  'Bebas Neue Regular': 'BebasNeue-Regular.ttf',
  'Barlow Condensed Regular': 'BarlowCondensed-Regular.ttf',
  'Barlow Condensed Italic': 'BarlowCondensed-Italic.ttf',
  'Barlow Condensed Bold Italic': 'BarlowCondensed-BoldItalic.ttf',
  'Barlow Condensed Bold': 'BarlowCondensed-Bold.ttf',
  'Anton Regular': 'Anton-Regular.ttf'
}