export const fonts = {
  "Bebas Neue Regular": "BebasNeue-Regular.ttf",
  "Belanosima Bold": "Belanosima-Bold.ttf",
  "Belanosima Regular": "Belanosima-Regular.ttf",
  "Belanosima SemiBold Regular": "Belanosima-SemiBold.ttf",
  "Berlin Sans FB Demi Regular": "BerlinSansFBDemi-Bold.ttf",
  "Bitter Regular": "Bitter-Regular.ttf",
  "Bitter Bold": "Bitter-Bold.ttf",
  "Bitter Italic": "Bitter-Italic.ttf",
  "Bitter Bold Italic": "Bitter-BoldItalic.ttf",
  "Cabin Bold Italic": "Cabin-BoldItalic.ttf",
  "Cabin Bold": "Cabin-Bold.ttf",
  "Cabin Italic": "Cabin-Italic.ttf",
  "Cabin Regular": "Cabin-Regular.ttf",
  "Carter One Regular": "CarterOne.ttf",
  "Chela One Regular": "ChelaOne-Regular.ttf",
  "Chewy Regular": "Chewy-Regular.ttf",
  "Comic Sans MS Bold Italic": "ComicSansMS-BoldItalic.ttf",
  "Comic Sans MS Bold": "ComicSansMS-Bold.ttf",
  "Comic Sans MS Italic": "ComicSansMS-Italic.ttf",
  "Comic Sans MS Regular": "ComicSansMS.ttf",
  "Damion Regular": "Damion.ttf",
  "Dancing Script Bold": "DancingScript-Bold.ttf",
  "Dancing Script Regular": "DancingScript-Regular.ttf",
  "Fraunces 72pt Bold Italic": "Fraunces72pt-BoldItalic.ttf",
  "Fraunces 72pt Bold": "Fraunces72pt-Bold.ttf",
  "Fraunces 72pt Italic": "Fraunces72pt-Italic.ttf",
  "Fraunces 72pt Regular": "Fraunces72pt-Regular.ttf",
  "Galada Regular": "Galada-Regular.ttf",
  "HelveticaRounded LT Std Bd Regular": "HelveticaRoundedLTStd-Bd.ttf",
  "Josefin Sans Bold Italic": "JosefinSans-BoldItalic.ttf",
  "Josefin Sans Bold": "JosefinSans-Bold.ttf",
  "Josefin Sans Italic": "JosefinSans-Italic.ttf",
  "Josefin Sans Regular": "JosefinSans-Regular.ttf",
  "Lato Bold Italic": "Lato-BoldItalic.ttf",
  "Lato Bold": "Lato-Bold.ttf",
  "Lato Italic": "Lato-Italic.ttf",
  "Lato Regular": "Lato-Regular.ttf",
  "League Spartan Bold": "LeagueSpartan-Bold.ttf",
  "League Spartan Regular": "LeagueSpartan-Regular.ttf",
  "Leckerli One Regular": "LeckerliOne-Regular.ttf",
  "Lexend Bold": "Lexend-Bold.ttf",
  "Lexend Deca Bold": "LexendDeca-Bold.ttf",
  "Lexend Deca Regular": "LexendDeca-Regular.ttf",
  "Lexend Regular": "Lexend-Regular.ttf",
  "Libre Baskerville Bold": "LibreBaskerville-Bold.ttf",
  "Libre Baskerville Regular": "LibreBaskerville-Regular.ttf",
  "Libre Baskerville Italic": "LibreBaskerville-Italic.ttf",
  "Lobster Regular": "Lobster-Regular.ttf",
  "Kanit Regular": "Kanit-Regular.ttf",
  "Kanit Bold": "Kanit-Bold.ttf",
  "Kanit Italic": "Kanit-Italic.ttf",
  "Kanit Bold Italic": "Kanit-BoldItalic.ttf",
  "Monoton Regular": "Monoton-Regular.ttf",
  "Noto Emoji Bold": "NotoEmoji-Bold.ttf",
  "Noto Emoji Light Regular": "NotoEmoji-Light.ttf",
  "Noto Emoji Medium Regular": "NotoEmoji-Medium.ttf",
  "Noto Emoji Regular": "NotoEmoji-Regular.ttf",
  "Noto Emoji SemiBold Regular": "NotoEmoji-SemiBold.ttf",
  "Noto Kufi Arabic Bold": "NotoKufiArabic-Bold.ttf",
  "Noto Kufi Arabic Regular": "NotoKufiArabic-Regular.ttf",
  "Noto Sans Bold Italic": "NotoSans-BoldItalic.ttf",
  "Noto Sans Bold": "NotoSans-Bold.ttf",
  "Noto Sans Devanagari Bold": "NotoSansDevanagari-Bold.ttf",
  "Noto Sans Devanagari Regular": "NotoSansDevanagari-Regular.ttf",
  "Noto Sans Display Bold Italic": "NotoSansDisplay-BoldItalic.ttf",
  "Noto Sans Display Bold": "NotoSansDisplay-Bold.ttf",
  "Noto Sans Display Italic": "NotoSansDisplay-Italic.ttf",
  "Noto Sans Display Regular": "NotoSansDisplay-Regular.ttf",
  "Noto Sans Hebrew Bold": "NotoSansHebrew-Bold.ttf",
  "Noto Sans Hebrew Regular": "NotoSansHebrew-Regular.ttf",
  "Noto Sans Italic": "NotoSans-Italic.ttf",
  "Noto Sans JP Bold": "NotoSansJP-Bold.ttf",
  "Noto Sans JP Regular": "NotoSansJP-Regular.ttf",
  "Noto Sans KR Bold": "NotoSansKR-Bold.ttf",
  "Noto Sans KR Regular": "NotoSansKR-Regular.ttf",
  "Noto Sans Malayalam Bold": "NotoSansMalayalam-Bold.ttf",
  "Noto Sans Malayalam Regular": "NotoSansMalayalam-Regular.ttf",
  "Noto Sans Mongolian Regular": "NotoSansMongolian-Regular.ttf",
  "Noto Sans Mono Bold": "NotoSansMono-Bold.ttf",
  "Noto Sans Mono Regular": "NotoSansMono-Regular.ttf",
  "Noto Sans Regular": "NotoSans-Regular.ttf",
  "Noto Sans SC Bold": "NotoSansSC-Bold.ttf",
  "Noto Sans SC Regular": "NotoSansSC-Regular.ttf",
  "Noto Sans TC Bold": "NotoSansTC-Bold.ttf",
  "Noto Sans TC Regular": "NotoSansTC-Regular.ttf",
  "Noto Sans Thai Bold": "NotoSansThai-Bold.ttf",
  "Noto Sans Thai Regular": "NotoSansThai-Regular.ttf",
  "Noto Serif SC Bold": "NotoSerifSC-Bold.ttf",
  "Noto Serif SC Regular": "NotoSerifSC-Regular.ttf",
  "Open Sans Bold Italic": "OpenSans-BoldItalic.ttf",
  "Open Sans Bold": "OpenSans-Bold.ttf",
  "Open Sans Italic": "OpenSans-Italic.ttf",
  "Open Sans Regular": "OpenSans-Regular.ttf",
  "Orbitron Bold": "Orbitron-Bold.ttf",
  "Orbitron Regular": "Orbitron-Regular.ttf",
  "Oswald Bold": "Oswald-Bold.ttf",
  "Oswald Regular": "Oswald-Regular.ttf",
  "PlaywriteAUSA Regular": "PlaywriteAUSA-Regular.ttf",
  "Poppins Bold Italic": "Poppins-BoldItalic.ttf",
  "Poppins Bold": "Poppins-Bold.ttf",
  "Poppins Italic": "Poppins-Italic.ttf",
  "Poppins Regular": "Poppins-Regular.ttf",
  "Potta One Regular": "PottaOne-Regular.ttf",
  "Pridi Bold": "Pridi-Bold.ttf",
  "Pridi Regular": "Pridi-Regular.ttf",
  "Roboto Bold Italic": "Roboto-BoldItalic.ttf",
  "Roboto Bold": "Roboto-Bold.ttf",
  "Roboto Italic": "Roboto-Italic.ttf",
  "Roboto Regular": "Roboto-Regular.ttf",
  "Rubik Regular": "Rubik-Regular.ttf",
  "Tahoma Bold": "Tahoma-Bold.ttf",
  "Tahoma Regular": "Tahoma.ttf",
  "Ubuntu Bold Italic": "Ubuntu-BoldItalic.ttf",
  "Ubuntu Bold": "Ubuntu-Bold.ttf",
  "Ubuntu Italic": "Ubuntu-Italic.ttf",
  "Ubuntu Regular": "Ubuntu-Regular.ttf",
  "Unicode BMP Fallback SIL Regular": "UnicodeBMPFallbackSIL.ttf",
  "Varela Regular": "Varela.ttf",
  "Yeseva One Regular": "YesevaOne-Regular.ttf",
  "Yesteryear Regular": "Yesteryear-Regular.ttf",
  "Zen Kaku Gothic New Bold": "ZenKakuGothicNew-Bold.ttf",
  "Zen Kaku Gothic New Regular": "ZenKakuGothicNew-Regular.ttf",
  "Zen Old Mincho Bold": "ZenOldMincho-Bold.ttf",
  "Zen Old Mincho Regular": "ZenOldMincho-Regular.ttf",
}
